language: python
python:
  - "3.8"
  - "3.5"

env:
  global:
    - LIBRARY_PATH='/home/travis/prefix/lib'
    - LD_LIBRARY_PATH='/home/travis/prefix/lib'
    - C_INCLUDE_PATH='/home/travis/prefix/include'
    - CPP_INCLUDE_PATH='/home/travis/prefix/include'

addons:
  apt:
    update: true
    packages:
      # These are packages needed for the libpostal build
      - curl
      - autoconf
      - automake
      - libtool
      - pkg-config
      # JRE is needed by the Stanford NER model
      - default-jre

cache:
  pip: true
  directories:
    # These are for caching compiled libpostal
    - /home/travis/prefix
    - /home/travis/libpostal
    # This is for caching the downloaded stanford_ner model
    - /home/travis/.scrubadub/stanford_ner
    # This is filled by textblob.download_corpora
    - /home/travis/nltk_data

before_install:
  # This installs libpostal, needed for the address parser
  - if test ! -f /home/travis/prefix/lib/libpostal.so ; then mkdir -p /home/travis/prefix /home/travis/libpostal &&
    git clone https://github.com/openvenues/libpostal /home/travis/libpostal && cd /home/travis/libpostal &&
    ./bootstrap.sh && ./configure --prefix=/home/travis/prefix && sudo make -j4 && sudo make install && cd - ; fi


# install python dependencies including this package in the travis
# virtualenv
install:
  - pip install -r requirements/python-dev
  - pip install -r requirements/python-extras-address
  - pip install -r requirements/python-extras-spacy
  - pip install -r requirements/python-extras-stanford
  # Needed for the TextBlob model
  - python -m textblob.download_corpora
  # One of the possible spacy models, should
  - python -m spacy download en_core_web_sm
  - pip install .
  # TODO: add stanford model download here?

# commands to run the testing suite. if any of these fail, travic lets us know
# Enabling type checking with mypy, but only showing the warning messages
script:
  - mypy --config-file setup.cfg scrubadub/
  - nosetests
  - flake8  --config setup.cfg scrubadub/
  - python3 ./tests/benchmark_accuracy.py --fast
  - python3 ./tests/benchmark_time.py
  - cd docs && make html && cd -

# commands to run after the tests successfully complete
after_success:
  - if test "$TRAVIS_PYTHON" != "3.5" ; then coveralls fi
